### PR TITLE
Reducing the number of objects created during sorting and removing bo…

### PR DESCRIPTION
**Pull request by kishoreg**
…ilet plate code

Sorting is creating too many objects unnecessarily. We just need two int arrays - 
int[size of dict]
int[num docs]

today we create
<data_type>[size of dict]
intiterator[size of dict]
int[num docs]

Overhead can be high for (long, string, bytes) columns and also proportional to the number of unique values in dictionary.

### CODE REVIEW

**Review by xiangfu0 — APPROVED** [review]

**Comment by Jackie-Jiang** [comment]
This can definitely reduce the memory usage, but will also increase the time spent on fetching values (doing O(nlogn) fetches vs O(n) before). Caching values on heap might cause problem for huge dictionaries, so still this change should be a good trade-off.

**Comment by kishoreg** [comment]
> This can definitely reduce the memory usage, but will also increase the time spent on fetching values (doing O(nlogn) fetches vs O(n) before). Caching values on heap might cause problem for huge dictionaries, so still this change should be a good trade-off.

Good point. However, note that sorting is common to both implementations. so the number of fetches are the same. It's just that in one case fetch is looking up an array (which is created by looking up the dictionary) and in another case, the lookup is on the dictionary. Given that this is for the consuming segment, the dictionary is mostly memory resident.

**Comment by Jackie-Jiang** [comment]
> > This can definitely reduce the memory usage, but will also increase the time spent on fetching values (doing O(nlogn) fetches vs O(n) before). Caching values on heap might cause problem for huge dictionaries, so still this change should be a good trade-off.
> 
> Good point. However, note that sorting is common to both implementations. so the number of fetches are the same. It's just that in one case fetch is looking up an array (which is created by looking up the dictionary) and in another case, the lookup is on the dictionary. Given that this is for the consuming segment, the dictionary is mostly memory resident.

For String and byte[], fetching from dictionary has extra cost to construct the Object (for String, read the bytes and decode the bytes, for byte[] copy the bytes into an array). IMO it's more like CPU bound instead of IO bound

**Comment by kishoreg** [comment]
We can optimize those things in another PR. We could potentially compare the byte[] without converting or copying. But as you said, the trade-off makes sense.

**Comment by Jackie-Jiang** [comment]
> We can optimize those things in another PR. We could potentially compare the byte[] without converting or copying. But as you said, the trade-off makes sense.

In the master PR, the comparison is handled inside MutableDictionary, which will make the future optimization much simpler as different MutableDictionary (on-heap/off-heap) should handle them differently.

**Pull request merged**
